name: Build Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Show repository contents
        run: |
          echo "Repository root:"
          ls -la

      - name: Build Docker image
        run: docker build --progress=plain -t task10-bioinfo:latest .

      - name: Check samtools
        run: docker run --rm task10-bioinfo:latest samtools --version

      - name: Check bcftools
        run: docker run --rm task10-bioinfo:latest bcftools --version

      - name: Check vcftools
        run: docker run --rm task10-bioinfo:latest vcftools --version

      - name: Check pysam
        run: docker run --rm task10-bioinfo:latest python3 -c "import pysam; print('pysam', pysam.__version__)"

      - name: Check REF/ALT script
        run: docker run --rm task10-bioinfo:latest python3 /opt/task10/alleles_to_ref_alt.py --help

      - name: Check environment variables
        run: |
          docker run --rm task10-bioinfo:latest bash -c 'echo "SOFT=$SOFT"'
          docker run --rm task10-bioinfo:latest bash -c 'echo "SAMTOOLS=$SAMTOOLS"'
          docker run --rm task10-bioinfo:latest bash -c 'echo "BCFTOOLS=$BCFTOOLS"'
          docker run --rm task10-bioinfo:latest bash -c 'echo "VCFTOOLS=$VCFTOOLS"'
